---
version: "2.3"
services:

  frontapp:
#https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx.html
    image: webdevops/php-nginx:7.4
    hostname: frontapp
    container_name: frontapp
    ports:
      - 8080:80
    networks:
      - main
    volumes:
      - ../api:/app
      - ./frontapp/symfony.conf:/etc/nginx/sites-enabled/default

  rabbit:
#https://hub.docker.com/_/rabbitmq
#guest / guest
    image: rabbitmq:3-management
    hostname: rabbit
    container_name: rabbit
    ports:
      - 8090:15672

  backapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: backapp
    container_name: backapp
    networks:
      - main
    volumes:
      - ../fakesms:/app
      - ./supervisor.conf/worker.conf:/opt/docker/etc/supervisor.d/worker.conf
      - ./backapp/symfony.conf:/etc/nginx/sites-enabled/default

  db:
    image: mysql:latest
    hostname: db
    container_name: db
    ports:
      - 8306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - main
    volumes:
      - ./db:/var/lib/mysql

networks:
  main:
    driver: bridge
